### ISSUE TITLE
iOS9 requirements needed

### ISSUE THREAD

**Issue by jason-laumeister** [Gigya-ClientServices/Gigya-iOS-ObjC-Demo#1]
Per Winston:

FYI for iOS9 there is are changes that break the demo. In order to get the iOS demo working I had to add to the plist the following (but this apparently is only a work around):

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
For more information please refer to this thread:

http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9

**Comment by chronosis** [comment]
Resolved in the 1.6 Release of the Demo
